global:
  scrape_interval: 15s
  evaluation_interval: 15s

# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['localhost:9093']  # Uncomment and configure when needed

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['app:8000']
    relabel_configs:
      - source_labels: [__address__]
        regex: "([^:]+):\\d+"
        target_label: instance
