# Generated by Django 4.2 on 2024-07-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='favourite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book',
            field=models.FileField(max_length=500, upload_to='books'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(max_length=500, upload_to='books_images'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_at',
            field=models.CharField(default='....', max_length=4),
        ),
    ]
