# Generated by Django 4.2 on 2024-07-27 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_author_updated_at_book_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedbook',
            old_name='purchased_at',
            new_name='created_at',
        ),
    ]
