# Generated by Django 4.2 on 2024-07-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_purchased_at_purchasedbook_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='price',
        ),
        migrations.AddField(
            model_name='purchase',
            name='word',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='PurchasedBook',
        ),
    ]
