# Generated by Django 4.2 on 2024-05-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_at',
            field=models.CharField(default='', max_length=4),
        ),
    ]
