# Generated by Django 4.2 on 2024-08-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_purchase_price_purchase_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='testing_word',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
