# Generated by Django 4.2 on 2024-08-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_purchase_testing_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
