# Generated by Django 4.2 on 2024-08-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='page_list',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
