# Generated by Django 4.2 on 2024-08-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_purchase_page_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='testing_word_list',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
