# Generated by Django 4.2 on 2024-08-19 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_purchase_testing_word_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
    ]
